### ISSUE TITLE
Make `name` part of the documented LuckyTask API

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky_task#6]
I override LuckyTask#name in some tasks because the obvious name for the task would otherwise collide with the names of my implementation classes. For example I want a task called "user.lookup", but I already have an implementation class called `User::Lookup`.

I can easily fix this by overriding LuckyTask#name, but that's an internal facility not documented or expected to stay the same between releases. Please document it.

**Comment by jwoertink** [comment]
Yeah, the `name` macro is definitely for that use case. 

We actually do have it documented...

https://github.com/luckyframework/lucky_task/blob/cee3f315251af27b3fc77e3ceabd8f2228e5d5ec/src/lucky_task/task.cr#L47-L61

As for documenting on the website, we have this issue open https://github.com/luckyframework/website/issues/725. For some reason the API docs for this shard aren't being generated.
